server.port=8080
spring.application.name=api-gateway

# Connect to Eureka Phonebook
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ⚠️ NOTICE THE NEW NAMESPACE PREFIX FOR SPRING BOOT 4 (server.webmvc)
# Route 1: Product Service
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/products/**

# Route 2: Order Service
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/orders/**