server.port=8082
spring.application.name=order-service

# H2 Console Configuration
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# Enable Circuit Breaker features in Actuator health endpoints (optional but good for tracking)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Resilience4j Circuit Breaker Properties
# We name our specific instance "productServiceCB"
resilience4j.circuitbreaker.instances.productServiceCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.productServiceCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.productServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.productServiceCB.permitted-number-of-calls-in-half-open-state=2